### ISSUE TITLE
Student_info.cc read_hw() fix. 

### ISSUE THREAD

**Issue by marcuspolk** [bitsai/book-exercises#10]
Hey I was having trouble with the names not being read correctly. Turns out that (in >> x) will NOT fail as expected if the the first char of the name is 'f', 'a', 'i', (possibly a few more chars, case insensitive). To fix this, you can either use getline() and then parse each line individually, or you can add a delimiter. I chose to go with a delimiter. Spent way too long trying to debug this lol. Hope it helps someone.

```cpp
istream& read_hw(istream& in, vector<double>& hw)
{
if (in) {
  hw.clear();
  double x;
  while (in >> x) 
     hw.push_back(x); 
  in.clear();
  in.ignore(std::numeric_limits<std::streamsize>::max(), '|');
  }
return in;
}
```

**Comment by bitsai** [comment]
hi @marcuspolk , good catch!  FWIW, this repository was only meant to be a record of my own attempts at various exercises, it wasn't intended to be an authoritative reference of any kind.  As such, please feel free to fork this repo (if you wish) and make improvements there, but I don't think I'll be taking any more pull requests or corrections going forward.
