### ISSUE TITLE
hey!

### ISSUE THREAD

**Issue by comp20141117** [bitsai/book-exercises#2]
Excuse me,This is I find in the encyclopedia of the definition of quartile,"quartile has three,the first quartile is called quartile,known as the lower quartile,the second quartile is the median,on the third quartile called quartile,respectively expressed in Q1 、Q2 and Q3 ",about quartile that you calculate in <accelerated c++> 3-2 that I don't really understand.

**Comment by bitsai** [comment]
@comp20141117 Hi there, thanks for writing in!  Basically, my code is wrong, because I didn't fully understand what quartiles are when I wrote it :/

I'm on an extended road trip right now.  But at some point in the next week or so I'll sit down and write a proper (hopefully) solution for 3-2.  Thanks for catching this!

**Comment by bitsai** [comment]
hi @comp20141117, I've updated exercise solution 3-2, and verified that it now generates quartiles as per Method 1 in the wiki article on quartiles:

https://en.wikipedia.org/wiki/Quartile

Thanks for letting me know about my mistake!  And please let me know if you spot anything else that looks wrong.

**Comment by khanhchung1997** [comment]
hi there, I have a question about 'median function'. How do you know that size = begin + end? I know it is correct but I do not really understand how it could be.

**Comment by khanhchung1997** [comment]
After a few minutes after I wrote the comment above, I understand it now. Thank you for the solution.

**Comment by bitsai** [comment]
@khanhchung1997 no problem at all :)

**Comment by khanhchung1997** [comment]
Even I solved this exercise by myself but when I compared my to yours, I felt ashamed. I learned something from your solution. Thank you so much.
