### ISSUE TITLE
The Solution of Exercise 4-4  in  _Accelerated C++_  is Not Right

### ISSUE THREAD

**Issue by jianyancheng** [bitsai/book-exercises#9]
Hi, I found that there might be a problem in your solution. When I input a double, `get_width` can't output right width.

The following  `get_width`  might solve the problem here:-)

``` c++
#include <cmath>

bool is_int(double n)
{
	return int(n) == n;
}

long long double2int(double n)
{
	if (long long(n) == n)
		return long long(n);
	else
		return double2int(10 * n);
}

int get_width(double n)
{
	return log10(double2int(n)) + 1;
}
```

**Comment by bitsai** [comment]
hi @jianyancheng, thanks for letting me know!  unfortunately I'm about to travel out of town for a family emergency, so it might be a little while before I can dig up my copy of Accelerated C++ and really look at this.  I'll do that as soon as I'm home (in about a week or so).

**Comment by bitsai** [comment]
hi @jianyancheng , sorry for the very late reply!  I discovered that I no longer have my copy of Accelerated C++ (I think I gifted it to a friend).  Also, this repository was only meant to be a record of my own attempts at various exercises, it wasn't intended to be an authoritative reference of any kind.

as such, please feel free to fork this repo (if you wish) and make improvements there, but I don't think I'll be taking any more pull requests or corrections going forward.
